name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  # renovate: datasource=github-releases depName=jdx/mise
  MISE_VERSION: 2026.7.7

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          version: ${{ env.MISE_VERSION }}

      - name: Run linter
        run: just lint

      - name: Build binary
        run: just build

      - name: Smoke test
        run: just run --help
